#!/usr/bin/env sh

# var
date=$(date +'%y_%m_%d')           # filename
lesson_date=$(date +'%d.%m.%y')    # lesson number
master=$(echo "$1")                # master file name
total_lesson=$(find *_*.tex | wc -l)
lesson_number=$(expr $total_lesson + 1)


# copy this string to file
echo -e \
"\\\cours{$lesson_number. $lesson_date}


%%% Local Variables:
%%% mode: latex
%%% TeX-master: \"${master%.*}\"
%%% End:" > $date.tex

# launch our favorite tex(t) editor
emacs $date.tex